---
model_type: yolo26s.pt
warmup_epochs: 3
epochs: 40
patience: 5
batch: 32
imgsz: 1024
lr0: 0.0005
lrf: 0.0015
optimizer: AdamW
mixup: 0.1
close_mosaic: 17
degrees: 5.0
translate: 0.2
iou: 0.6
box: 4.19
cls: 5.28
dfl: 6.64
