---
stages:
  fetch_model_input:
    cmd:
      - >-
        uv run dvc get https://github.com/pyronear/pyro-dataset
        data/processed/yolo_train_val --rev v2.0.0
        --out ./data/01_model_input/yolo_train_val
        ||
        uv run dvc get git@github.com:pyronear/pyro-dataset.git
        data/processed/yolo_train_val --rev v2.0.0
        --out ./data/01_model_input/yolo_train_val
    outs:
      - ./data/01_model_input/yolo_train_val

  train_yolo_best:
    cmd:
      - >-
        uv run python ./scripts/data/model_input/build.py
        --input-dir ./data/01_model_input/yolo_train_val
        --output-dir ./data/01_model_input/yolo_train_val_small
        --sampling-ratio 0.01
        --random-seed 0
        --loglevel info
      - >-
        uv run python ./scripts/model/yolo/train.py
        --data ./data/01_model_input/yolo_train_val_small/datasets/data.yaml
        --config ./scripts/model/yolo/configs/best.yaml
        --output-dir ./data/02_models/yolo/
        --experiment-name best
        --loglevel info
    deps:
      - ./scripts/data/model_input/build.py
      - ./scripts/model/yolo/train.py
      - ./scripts/model/yolo/configs/best.yaml
      - ./data/01_model_input/yolo_train_val
    outs:
      - ./data/02_models/yolo/best

  build_manifest_yolo_best:
    cmd:
      - >-
        uv run python ./scripts/model/yolo/build_manifest.py
        --save-dir ./data/03_reporting/yolo/best/
        --dir-model ./data/02_models/yolo/best/
        --loglevel info
    deps:
      - ./scripts/model/yolo/build_manifest.py
      - ./data/02_models/yolo/best/
    outs:
      - ./data/03_reporting/yolo/best/

  fetch_sequential_val:
    cmd:
      - >-
        uv run dvc get https://github.com/pyronear/pyro-dataset
        data/processed/sequential_train_val/val --rev v2.0.0
        --out ./data/01_model_input/sequential_train_val/val
        ||
        uv run dvc get git@github.com:pyronear/pyro-dataset.git
        data/processed/sequential_train_val/val --rev v2.0.0
        --out ./data/01_model_input/sequential_train_val/val
    outs:
      - ./data/01_model_input/sequential_train_val/val

  export_yolo_best:
    matrix:
      format: [onnx, ncnn]
      device: [cpu, mps]
    cmd:
      - >-
        uv run python ./scripts/model/yolo/export.py
        --output-dir ./data/02_models/yolo-export/best/
        --model-dir ./data/02_models/yolo/best/
        --format ${item.format}
        --device ${item.device}
        --loglevel info
    deps:
      - ./scripts/model/yolo/export.py
      - ./data/02_models/yolo/best/
    outs:
      - ./data/02_models/yolo-export/best/${item.format}/${item.device}

  evaluate_sequential_yolo_best:
    cmd:
      - >-
        uv run python ./scripts/model/yolo/evaluate_sequential.py
        --model-path ./data/02_models/yolo-export/best/onnx/cpu/best.onnx
        --data-dir ./data/01_model_input/sequential_train_val/val
        --output-dir ./data/03_reporting/yolo/sequential/best/
        --max-frames 15
        --loglevel info
    deps:
      - ./scripts/model/yolo/evaluate_sequential.py
      - ./data/02_models/yolo-export/best/onnx/cpu
      - ./data/01_model_input/sequential_train_val/val
    outs:
      - ./data/03_reporting/yolo/sequential/best/
